name: Publish Nuget Packages

on:
  push:
    branches:
      - main
      - release/**
    paths:
      - version.json
      - .github/workflows/nuget-publish.yml
      - Directory.Build.props
      - "**/*"
      - "!**/*.md"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x

      # Versions
      - uses: dotnet/nbgv@master
        id: rtk_version
        with:
          setAllVars: true

      # Publish RTK
      - name: Build Packages
        run: |
          dotnet restore
          dotnet build -p:Configuration=Release
          dotnet pack -p:Configuration=Release

      # NuGet Push
      - name: Push package to Nuget registry
        run: |
          dotnet nuget push CustomExtensions.WinUI\bin\Release\CustomExtensions.WinUI.${{ steps.rtk_version.outputs.NuGetPackageVersion }}.nupkg -k $env:NUGET_PUBLISH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_PUBLISH_TOKEN: ${{ secrets.NUGET_PUBLISH_TOKEN }}
